CREATE TABLE IF NOT EXISTS WORKFLOW
(
  ID_ VARCHAR(64) PRIMARY KEY,
  KEY_ BIGINT,
  BPMN_PROCESS_ID_ VARCHAR(64),
  VERSION_ INT,
  RESOURCE_ TEXT,
  TIMESTAMP_ BIGINT,
  INDEX WORKFLOW_ID_INDEX (ID_),
  INDEX WORKFLOW_KEY_INDEX (KEY_)
);

CREATE TABLE IF NOT EXISTS WORKFLOW_INSTANCE
(
	ID_ VARCHAR(64) PRIMARY KEY,
	PARTITION_ID_ INT,
	KEY_ BIGINT,
  BPMN_PROCESS_ID_ VARCHAR(64),
  VERSION_ INT,
	WORKFLOW_KEY_ BIGINT,
	STATE_ VARCHAR(255),
  START_ BIGINT,
  END_ BIGINT,
  INDEX WORKFLOW_INSTANCE_ID_INDEX (ID_),
  INDEX WORKFLOW_INSTANCE_WORKFLOW_KEY_INDEX (WORKFLOW_KEY_)
);

CREATE TABLE IF NOT EXISTS ACTIVITY_INSTANCE
(
	ID_ VARCHAR(64) PRIMARY KEY,
	PARTITION_ID_ INT,
	KEY_ BIGINT,
	INTENT_ VARCHAR(255),
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ACTIVITY_ID_ VARCHAR(64),
	SCOPE_INSTANCE_KEY_ BIGINT,
	PAYLOAD_ TEXT,
	WORKFLOW_KEY_ BIGINT,
  TIMESTAMP_ BIGINT,
    INDEX ACTIVITY_INSTANCE_ID_INDEX (ID_),
    INDEX ACTIVITY_INSTANCE_WORKFLOW_INSTANCE_KEY_INDEX (WORKFLOW_INSTANCE_KEY_)
);

CREATE TABLE IF NOT EXISTS INCIDENT
(
	ID_ VARCHAR(64) PRIMARY KEY,
	KEY_ BIGINT,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ACTIVITY_INSTANCE_KEY_ BIGINT,
	JOB_KEY_ BIGINT,
	ERROR_TYPE_ VARCHAR(255),
	ERROR_MSG_ VARCHAR(2048),
  TIMESTAMP_ BIGINT,
  INDEX INCIDENT_ID_INDEX (ID_),
  INDEX INCIDENT_WORKFLOW_INSTANCE_KEY_INDEX (WORKFLOW_INSTANCE_KEY_)
);
