DROP INDEX IF EXISTS WORKFLOW_KEY_INDEX;
DROP INDEX IF EXISTS WORKFLOW_INSTANCE_WORKFLOW_KEY_INDEX;
DROP INDEX IF EXISTS ELEMENT_WORKFLOW_INSTANCE_KEY_INDEX;
DROP INDEX IF EXISTS INCIDENT_WORKFLOW_INSTANCE_KEY_INDEX;
DROP INDEX IF EXISTS JOB_WORKFLOW_INSTANCE_KEY_INDEX;
DROP INDEX IF EXISTS MSG_SUB_WORKFLOW_INSTANCE_KEY_INDEX;
DROP INDEX IF EXISTS TIMER_ELEMENT_INSTANCE_KEY_INDEX;
DROP INDEX IF EXISTS VARIABLE_WORKFLOW_INSTANCE_KEY_INDEX;

CREATE TABLE IF NOT EXISTS WORKFLOW
(
  ID_ VARCHAR PRIMARY KEY,
  KEY_ BIGINT,
  BPMN_PROCESS_ID_ VARCHAR,
  VERSION_ INT,
  RESOURCE_ VARCHAR,
  TIMESTAMP_ BIGINT
);

CREATE INDEX WORKFLOW_KEY_INDEX ON WORKFLOW(KEY_) ;

CREATE TABLE IF NOT EXISTS WORKFLOW_INSTANCE
(
	ID_ VARCHAR PRIMARY KEY,
	PARTITION_ID_ INT,
	KEY_ BIGINT,
  BPMN_PROCESS_ID_ VARCHAR,
  VERSION_ INT,
	WORKFLOW_KEY_ BIGINT,
	STATE_ VARCHAR,
  START_ BIGINT,
  END_ BIGINT
);

CREATE INDEX WORKFLOW_INSTANCE_WORKFLOW_KEY_INDEX ON WORKFLOW_INSTANCE(WORKFLOW_KEY_);

CREATE TABLE IF NOT EXISTS ELEMENT_INSTANCE
(
	ID_ VARCHAR PRIMARY KEY,
	PARTITION_ID_ INT,
	KEY_ BIGINT,
	INTENT_ VARCHAR,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ELEMENT_ID_ VARCHAR,
	FLOW_SCOPE_KEY_ BIGINT,
	WORKFLOW_KEY_ BIGINT,
  TIMESTAMP_ BIGINT
);

CREATE INDEX ELEMENT_WORKFLOW_INSTANCE_KEY_INDEX ON ELEMENT_INSTANCE(WORKFLOW_INSTANCE_KEY_);

CREATE TABLE IF NOT EXISTS INCIDENT
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	BPMN_PROCESS_ID_ VARCHAR,
	WORKFLOW_KEY_ BIGINT,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ELEMENT_INSTANCE_KEY_ BIGINT,
	JOB_KEY_ BIGINT,
	ERROR_TYPE_ VARCHAR,
	ERROR_MSG_ VARCHAR,
  CREATED_ BIGINT,
  RESOLVED_ BIGINT
);

CREATE INDEX INCIDENT_WORKFLOW_INSTANCE_KEY_INDEX ON INCIDENT(WORKFLOW_INSTANCE_KEY_);

CREATE TABLE IF NOT EXISTS JOB
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	JOB_TYPE_ VARCHAR,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ELEMENT_INSTANCE_KEY_ BIGINT,
	STATE_ VARCHAR,
	RETRIES_ INT,
	WORKER_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE INDEX JOB_WORKFLOW_INSTANCE_KEY_INDEX ON JOB(WORKFLOW_INSTANCE_KEY_);

CREATE TABLE IF NOT EXISTS MESSAGE
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	NAME_ VARCHAR,
	CORRELATION_KEY_ VARCHAR,
	MESSAGE_ID_ VARCHAR,
	PAYLOAD_ VARCHAR,
	STATE_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE TABLE IF NOT EXISTS MESSAGE_SUBSCRIPTION
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	ELEMENT_INSTANCE_KEY_ BIGINT,
	MESSAGE_NAME_ VARCHAR,
	CORRELATION_KEY_ VARCHAR,
	STATE_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE INDEX MSG_SUB_WORKFLOW_INSTANCE_KEY_INDEX ON MESSAGE_SUBSCRIPTION(WORKFLOW_INSTANCE_KEY_);

CREATE TABLE IF NOT EXISTS TIMER
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	ELEMENT_INSTANCE_KEY_ BIGINT,
	HANDLER_NODE_ID_ VARCHAR,
	DUE_DATE_ BIGINT,
	STATE_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE INDEX TIMER_ELEMENT_INSTANCE_KEY_INDEX ON TIMER(ELEMENT_INSTANCE_KEY_);

CREATE TABLE IF NOT EXISTS WORKER
(
	ID_ VARCHAR PRIMARY KEY,
	WORKER_ VARCHAR,
	JOB_TYPE_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE TABLE IF NOT EXISTS VARIABLE
(
	ID_ VARCHAR PRIMARY KEY,
	KEY_ BIGINT,
	NAME_ VARCHAR,
	VALUE_ VARCHAR,
	WORKFLOW_INSTANCE_KEY_ BIGINT,
	SCOPE_KEY_ BIGINT,
	STATE_ VARCHAR,
	TIMESTAMP_ BIGINT
);

CREATE INDEX VARIABLE_WORKFLOW_INSTANCE_KEY_INDEX ON VARIABLE(WORKFLOW_INSTANCE_KEY_);
